#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::RealBin/../lib";

use Era::Command::autoreview;

@ARGV = () if ($ARGV[0] // '') =~ qr/^(-h|(--)?help)$/;

my $ret = Era::Command::autoreview->new->run(@ARGV);
exit $ret unless $ENV{MOJO_HELP};